ChatGPTNextWeb/NextChat

- app/components/home.module.scss
- app/components/home.tsx
1. 在回复 loading 状态时，隐藏 action bar
2. 在回复内容较少时，action bar 样式问题
> fix: message top action style issue

- app/components/home.module.scss
- app/components/home.tsx
> fix: send button covering the text in the textarea

- app/components/home.tsx
> onUserSubmit hide promptHints

- app/components/home.tsx
> feat: setUserInput with onDoubleClickCapture in mobile phone

- app/locales/cn.ts
- app/locales/en.ts
- app/locales/es.ts
- app/locales/index.ts
- app/locales/tw.ts
Hello @Yidadaa ,
I have created a fork of the ChatGPT-Next-Web project and added or updated the locales to support the Spanish language. I have done some testing and everything seems to be working correctly.
I hope you find these updates useful, and if you have any questions or suggestions, please don't hesitate to let me know.
Thank you for your time and effort on this project!
Best regards
> Update: locales in spanish

- app/components/home.tsx
Add confirm tips when deleting conversation on pc.
> feat: add confirm tips when deleting conversation on pc

- app/components/home.tsx
顺便完善了ts的类型.阻止使用中文输入法的enter发送消息逻辑
> fix: #331 修复中文输入法下enter错误发送消息问题

- app/components/chat.tsx
- app/locales/cn.ts
- app/locales/en.ts
- app/locales/es.ts
- app/locales/it.ts
- app/locales/tw.ts
优化了聊天记录的导出内容，现在能够更容易区分显示哪些消息是来自用户的，哪些是来自ChatGPT的。
> [opt]  Optimize the display of exported chat history content.

- app/components/chat.tsx
- app/components/settings.tsx
- app/utils.ts
> fix 头像无法正常显示 

- app/utils.ts
期望：在pc或mobile phone能够复制
实际结果：部署服务器后，在mac以及手机端无法复制
解决：优化复制逻辑，实测成功
> fix(utils): 修复复制问题

- app/components/chat-list.tsx
- app/components/home.module.scss
- app/components/home.tsx
- app/store/app.ts
- package.json
- yarn.lock
引入 [dnd](https://github.com/hello-pangea/dnd) 实现拖拽 Session 的功能。
> Drag & Drop support for ChatList

- docs/faq-cn.md
> docs: 更新中文FAQ faq-cn.md

- app/components/button.module.scss
- app/components/button.tsx
- app/components/chat.tsx
Optimize component `IconButton`.
Use `button` instead of `div`, and add `disabled` property.
> refactor: optimize component `IconButton`

- Dockerfile
- README.md
- README_CN.md
- scripts/fetch-prompts.mjs
> feat: #120 docker proxy

- app/locales/cn.ts
- app/locales/en.ts
- app/locales/es.ts
- app/locales/index.ts
- app/locales/it.ts
- app/locales/jp.ts
- app/locales/tr.ts
- app/locales/tw.ts
> add Japanese

- app/components/chat.tsx
Reverts Yidadaa/ChatGPT-Next-Web#715
This shit SUCKS.
> Revert "fix: autoscroll conflict"

- .github/workflows/sync.yml
增加执行[错误提示](https://github.com/yorunning/ChatGPT-Next-Web/actions/runs/4680039557/jobs/8290866423#step:4:1)
> ci(sync): add an error prompt

- app/locales/tw.ts
> feat: close #796 improve tw summarize title prompt

- app/locales/cn.ts
- app/locales/de.ts
- app/locales/en.ts
- app/locales/es.ts
- app/locales/index.ts
- app/locales/it.ts
- app/locales/jp.ts
- app/locales/tr.ts
- app/locales/tw.ts
- app/store/app.ts
translated by gpt-4 and post-processed by a native speaker :)
> Add german language translation de.ts

- package.json
- yarn.lock
解决windows环境下，本地开发报错
```
error - SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse ()
```
close https://github.com/Yidadaa/ChatGPT-Next-Web/issues/863
> fix:  #863 errors on windows

- app/locales/cn.ts
- app/locales/jp.ts
- app/locales/tw.ts
> fix user prompt translation

- app/api/common.ts
Added support for organization ID
> Added support for organization ID

- scripts/fetch-prompts.mjs
Although mirrors have been used to avoid the problem of mainland China's inability to access `raw.githubusercontent.com`, actual tests have shown that there are still blockages in accessing this mirror address from mainland China, which can cause construction and testing processes to be blocked. I believe a timeout should be added to avoid this situation.
> fix typo & add timeout to stuck request

- app/locales/tw.ts
> Improve tw locale

- app/components/mask.tsx
> fix: mask download not working #1119

- app/components/markdown.tsx
Resolved Markdown Issue
This pull request resolves an issue where internal links were not redirecting properly in markdown, and optimizes the behavior for external links to open in a new window.
> fix: Resolve markdown link issue

- Dockerfile
[npm mirror](https://npmmirror.com/)
> chore: update registry mirror

- app/components/chat.tsx
> refactor: determine userInput by trimming

- app/locales/cn.ts
- app/locales/de.ts
- app/locales/en.ts
- app/locales/es.ts
- app/locales/index.ts
- app/locales/it.ts
- app/locales/jp.ts
- app/locales/ru.ts
- app/locales/tr.ts
- app/locales/tw.ts
- app/locales/vi.ts
Adding a Russian translation and fixing other language files to make them look the same.
> Adding Russian translation

- app/components/chat.tsx
this is the fix of https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1413, hope it works.
> Fix bug #1413 hotkey clashes

- README.md
the 3 new languages, namely `Tiếng Việt`, `Русский`,` Čeština`, should reflect in README.md
> docs: add supported languages to README.md

- app/components/chat-list.tsx
cmd/alt/ctrl ↑ ↓ 时候切换聊天窗口，侧边栏自动滚动
cmd/alt/ctrl ↑ ↓ Switch the chat window at any time, and the sidebar will scroll automatically
> feat: scrolling effect when switching chat windows

- Dockerfile
Fix connect error when using proxy
> fix: add localnet to proxychains config

- app/client/platforms/openai.ts
for the explanation, please see ticket https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1553
> fix: #1533 handle non-stream type

- app/masks/cn.ts
java 开发工程师，监控平台项目
好的，以下是您需要的通用简历：
```
姓名：张三
出生年月：1990年1月
学历：本科
面试职位：Java开发工程师
工作年限：5年
意向城市：北京
1. 熟练掌握Java编程语言，熟悉面向对象编程思想；
2. 熟悉Spring、SpringMVC、Mybatis等主流开源框架；
3. 熟悉常用的关系型数据库MySQL、Oracle等，熟悉SQL语言；
4. 熟悉Linux操作系统，熟悉常用的命令行操作；
5. 熟悉Git等版本控制工具；
6. 熟悉常用的前端技术，如HTML、CSS、JavaScript等；
7. 熟悉Redis、MongoDB等非关系型数据库；
8. 熟悉SpringBoot、SpringCloud等微服务框架；
9. 熟悉Docker等容器技术；
10. 熟悉消息中间件Kafka等。
1. 公司名称：ABC科技有限公司
工作时间：2018年6月至今
工作职责：负责监控平台项目的开发和维护，参与需求分析、系统设计、编码、测试、上线等工作，负责技术方案的评审和制定，协调前后端开发人员完成项目开发，解决项目中遇到的技术难点和问题。
2. 公司名称：DEF软件有限公司
工作时间：2016年7月至2018年5月
工作职责：参与公司内部OA系统的开发和维护，负责系统模块的设计和开发，编写相应的技术文档，协调测试人员进行测试，解决项目中遇到的技术问题。
1. 项目名称：监控平台
项目背景：该项目是为了解决公司内部各个系统监控不够全面、监控数据不够准确、监控告警不够及时等问题而开发的。该项目通过采集各个系统的运行数据，对数据进行分析和处理，生成相应的监控报表和告警信息，提高了系统的监控和管理能力。
项目细节：本人负责了监控平台的后端开发工作，使用了SpringBoot、Mybatis等主流框架进行开发。使用Redis、MongoD …
```
> add new mask 简历写手

- app/locales/index.ts
Reverts Yidadaa/ChatGPT-Next-Web#1648
> Revert "Not to detect user lang when running in Node"

- Dockerfile
> fix: #1747 docker file bug

- app/api/common.ts
Vercel Logs:
[OpenAI]  TypeError: Can't modify immutable headers.
at (app/api/common.ts:55:25)
at (app/api/openai/[...path]/route.ts:20:11)
at (node_modules/next/dist/server/future/route-modules/app-route/module.js:246:36)
issues: #1746
> fix: #1746 Can't modify immutable headers.

- app/components/home.module.scss
> fix: style typo error in home.module.scss

- docker-compose.yml
> fix docker-compose.yml bug

- app/components/auth.tsx
> feat: 修改 auth.tsx 输入框为password

- app/locales/jp.ts
fixed Japanese Translation by native speaker.
But some parts are still not natural, I will fix them later.
> Fix Japanese language file

- src-tauri/Cargo.toml
- src-tauri/src/main.rs
> restore last window state (position and size) on startup

- app/store/chat.ts
A possible fix for issue #2111.
> fix: #2111 make "Attached Messages Count" working

- app/locales/jp.ts
Add translation for some setting items:
- Input Template
- Reset All Settings
- Clear All Data
> Update Japanese translation

- app/components/ui-lib.module.scss
> fix: selector z-index bug

- app/client/platforms/openai.ts
本地开发时候，接口异常时候`，resJson.data`数据不是数组，就有错误提示
> perf:  models接口返回异常数据的容错处理

- app/api/common.ts
> fix: typos

- app/store/mask.ts
> fix: 迁移面具对象的key以解决无法编辑旧面具的问题

- app/store/chat.ts
> fix: enable `enableInjectSystemPrompts` attribute for old sessions

- app/components/settings.tsx
- app/locales/cn.ts
- app/locales/en.ts
- app/store/chat.ts
- app/store/config.ts
> add autoGenerateTitle checkbox

- app/components/markdown.tsx
Improvement in handling text direction for each paragraph.
Check the second paragraph in the screenshots below:
Before:
After:
Thank you once again for the incredible UI.
> Improving text direction for each paragraph

- app/locales/tw.ts
Adoption of text that is more closely aligned with the usage of zh-tw
> Improve the text in tw.ts

- app/components/chat.module.scss
- app/styles/globals.scss
Specific editIcon styles for iOS devices.
before:
after:
> Specific EditIcon styles for iOS devices

- app/components/exporter.tsx
Continue from https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2692
[+] A view looks better
[+] auto minify json when click a copy in markdown and download
> [Feature] Better JSON Exporter

- scripts/setup.sh
there is a bug in setup.sh in line 13. there should not be  a blank Space after “!”.
and i added support for debian system.
> Fixed the bug of setup.sh when centos system and added support for debian system

- app/components/exporter.tsx
- app/locales/ar.ts
- app/locales/bn.ts
- app/locales/cn.ts
- app/locales/cs.ts
- app/locales/de.ts
- app/locales/en.ts
- app/locales/es.ts
- app/locales/fr.ts
- app/locales/id.ts
- app/locales/index.ts
- app/locales/it.ts
- app/locales/jp.ts
- app/locales/ko.ts
- app/locales/ru.ts
- app/locales/tr.ts
- app/locales/tw.ts
- app/locales/vi.ts
[[+] Language indonesia (my country)](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2705/commits/507b7fee56b8c63ffee6bbbe684f4acedaf27640)
[[+] FineTuned Sysmessage Depends for local language](https://github.com/Yidadaa/ChatGPT-Next-Web/pull/2705/commits/e6cc1625b5e13b899d75a0ef35f2010b510fa721)
> [+] Language indonesia & FineTuned Sysmessage

- package.json
- yarn.lock
Reverts Yidadaa/ChatGPT-Next-Web#2673
> Revert "chore(deps): bump next from 13.4.9 to 13.4.19"

- app/locales/jp.ts
Added the missing part of the Japanese translation.
> improve japanese translations

- app/components/auth.tsx
- Made changes to the Auth Page to reset the input field for the access code when the "Later" button is clicked. This ensures that only expected user is logged by entering access code or entering their OpenAI API Key, mitigating the risk of small bug issue
> [+] Updated Auth Page

- .env.template
This line of comment is misplaced here.
> fix: misleading comment

- app/components/sidebar.tsx
[+] fix(sidebar.tsx): update onClick function to conditionally navigate to different paths based on config.dontShowMaskSplashScreen value
Ref : [Feature] Make the mask selection more streamlined Yidadaa#2895
> UI Page [sidebar]

- app/store/sync.ts
> Fix typo in sync.ts

- app/components/mask.tsx
[+] refactor(mask.tsx): refactor simple search to be case-insensitive
> Refactor Mask UI Page [Masks]

- public/serviceWorker.js
Caching files by workbox to fast access in weak network
> fix serviceWorker cache: auto caching files by workbox

- public/serviceWorker.js
> fix: #3074 Revert "fix serviceWorker cache: auto caching files by workbox"

- .env.template
> docs: fix typo in #3171

- app/components/settings.tsx
[+] fix(settings.tsx): fix condition to show balance query in settings component
[+] fix(settings.tsx): add condition to hide balance query for app clients
> Fix UI/UX Page [Settings]

- app/api/common.ts
- [+] fix(common.ts): fix console.log statement for [Org ID] to handle undefined value
> Fix Api Common [Server Side] [Console Log]

- README.md
- [+] chore(README.md): add support for Korean and Indonesian languages
> [!NOTE]  
>  This docs are missing in CN
> Chore Docs (README.md)

- app/utils.ts
- [+] fix(utils.ts): fix trimTopic function to remove double quotes from the start and end of the string, and remove specified punctuation from the end of the string
> Fix Trim Topic in Indonesia Language

- app/components/emoji.tsx
try to fix: https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/issues/3531
> fix: update emoji url

- .github/workflows/sync.yml
> fix sync.yml

- .env.template
- Dockerfile
- README.md
- README_CN.md
- app/api/common.ts
- app/api/google/[...path]/route.ts
- app/client/api.ts
- app/client/platforms/google.ts
- app/client/platforms/openai.ts
- app/components/auth.tsx
- app/components/exporter.tsx
- app/components/home.tsx
- app/components/model-config.tsx
- app/components/settings.tsx
- app/config/server.ts
- app/constant.ts
- app/locales/cn.ts
- app/locales/en.ts
- app/store/access.ts
- app/store/chat.ts
- app/store/update.ts
- app/utils/model.ts
- docker-compose.yml
Relate Issue: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3543
> [Feature] support Gemini Pro API

- app/client/api.ts
- app/utils/model.ts
Issue: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3618
> Fix Issue: ChatGPTNextWeb#3618

- app/api/auth.ts
- app/config/server.ts
> Fix [Bug] Issue ChatGPTNextWeb#3615

- app/locales/index.ts
- app/locales/sk.ts
Slovak language was added app/locales/sk.ts and also the language was added to app/locales/index.ts
> Added Slovak language support

- .github/workflows/deploy_preview.yml
- scripts/delete-deployment-preview.sh
> fix: cicd, delete vercel pre

- .github/workflows/deploy_preview.yml
- .github/workflows/remove_deploy_preview.yml
- scripts/delete-deployment-preview.sh
> fix: cicd, delete velcel pre

- app/constant.ts
- [+] feat(constant.ts): add 'gemini-pro' to KnowledgeCutOffDate constant
> Feat [UI/UX] [Constants] [Models] gemini-pro KnowledgeCutOffDate

- .github/workflows/app.yml
> ci: build universal binary for macos

- .github/workflows/deploy_preview.yml
The vercel deploy preview it's not updating related to this pr
- ChatGPTNextWeb#4003
> Fix [CI/CD] [Vercel] Deploy Preview

- next.config.mjs
> chore: fix typo in next.config.mjs

- app/locales/tw.ts
I have translated previously untranslated text in `tw.ts`
[tw.ts更改預覽](https://4142-vercelpreviewdeployment.pr.nextchat.dev/) 請選擇繁體中文
> feat(tw.ts): added new translations

- app/constant.ts
Source: https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
> Correct cutoff dates

- app/client/platforms/openai.ts
fix vision model  text truncation issue
- #4084
> fix: add max_tokens when using vision model

- app/locales/tw.ts
slightly polishes the tw text in `tw.ts`.
[Vercel Preview](https://chat-gpt-next-ixe6x7qiw-aliceric27s-projects.vercel.app/) 稍微修改繁體語系字詞
> slightly polishes the tw text.

- app/api/webdav/[...path]/route.ts
> [Cherry Pick] Fix Webdav Syncing Issues

- app/components/mask.tsx
> The language filtering option of the mask is stored

- .dockerignore
> fix docker

- app/components/message-selector.tsx
fix https://github.com/Yidadaa/ChatGPT-Next-Web/commit/be6d45e49f1df90daba4625117b95903189891c2#r133754690
> fix: MessageSelectorWarning

- app/client/platforms/openai.ts
[+] fix(openai.ts): fix parsing error in ChatGPTApi's message handler
[+] feat(openai.ts): add logging for flagged categories in text moderation
This only console log for handling this text moderation, for Azure provider since azure already have text-moderation, and its enabled by default on their service
> Feat ChatGPT LLM Api [Console Log] [Text Moderation] [Azure]

- app/store/chat.ts
[+] chore(chat.ts): remove unnecessary comment and refactor variable name
[+] feat(chat.ts): add stream: false to config object
> Refactor Summarize Logic

- app/components/auth.tsx
- app/locales/cn.ts
- app/locales/en.ts
feat: fix lang support
feat: auth page setting for claude api
> Feat [UI/UX Page] [Auth] Add input box for claude api on auth page

- app/api/webdav/[...path]/route.ts
- app/store/sync.ts
- app/utils/cloud/webdav.ts
modify the logtics of concatenating url for webdav proxy forwarding request
> feat: fix webdav 逻辑

- app/locales/tw.ts
- app/masks/index.ts
- app/masks/tw.ts
> Improve tw Traditional Chinese locale

- app/utils.ts
https://platform.openai.com/docs/guides/vision
> gpt-4o as vision model

- README_CN.md
> readme_cn 补充锚点

- app/components/markdown.tsx
> hotfix Mermaid can not render. close #5374

- app/api/anthropic.ts
> fix: ts error

- app/api/google.ts
> fix: build error

- app/utils/chat.ts
> hotfix plugin result is not string #5614

- .github/workflows/test.yml
> update test run target

- app/client/platforms/google.ts
> hotfix for gemini invald argument #5715

- README.md
- README_CN.md
> chore: update readme

- app/constant.ts
> fix: glm chatpath

- app/client/platforms/glm.ts
- app/constant.ts
> feature: support glm-4v
