ChatGPTNextWeb/NextChat

app/components/home.tsx
新建会话后关闭侧边栏。
在桌面端上未产生影响，移动端可修复 #82 。
=> fix: fix #82, close sidebar after new session

app/styles/markdown.scss
解决代码太长时”copy“按钮随横向滚动条移动的问题。
修复后，”copy“按钮固定在右上角，不随横向滚动条移动。
**BEFORE:**
**AFTER:**
=> fix: code copy button position

app/components/home.tsx, app/store/app.ts
1. 加入了 CMD/Meta + Enter 的快捷键功能，对 MacOS/Linux 用户更友好。
2. 在使用快捷键发送消息时默认启动下滑动画，但使用“发送”按钮发送消息并不会，改用 `mousedown` 事件 + `element.contains` 判断行为是否聚焦在输入框内。
=> feat: CmdEnter config for submitkey, bug fix for auto scrolling

app/components/home.tsx, app/components/settings.tsx, app/locales/cn.ts, app/locales/en.ts, app/locales/tw.ts, app/store/app.ts
有时候在移动端或者 HiDPI 的显示器上，14px 的字体可能会感觉有点小，添加了一个设置可以改变聊天内容的字体大小
=> feat: add font size config

app/components/home.tsx, app/components/markdown.tsx, app/locales/cn.ts, app/locales/en.ts, app/locales/tw.ts, app/styles/markdown.scss
在Enter发送模式下，使用Meta+Enter对文本进行换行。并使ReactMarkdown组件正常显示换行符
=> supports the display of line breaks in Markdown

app/components/markdown.tsx, app/styles/markdown.scss
=> fix: dialog height

app/components/markdown.tsx, package.json
引入remark-breaks 插件解决 ReactMarkdown 组件不渲染换行问题，同时避免了底部边距问题 #162
=> feat: import remark-breaks plugin

app/components/home.module.scss, app/styles/globals.scss
=> 修复在移动端高度被搜索栏占用导致无法完整显示一屏问题

.github/workflows/sync.yml
之前的同步代码有问题，因为`TG908/fork-sync@v1.1`已经不存在了。已经修复了这个问题并经过了测试，但是还有几个隐含的问题：
1.在同步后，相对于上游仓库会多一个提交记录，这会导致版本检测时使用领先一个提交的版本号；
2.默认生成的`GITHUB_TOKEN`没有更新workflow配置文件的权限，这意味着如果上游仓库中的其他的workflow配置文件(如:docker.yml)发生更新，下游仓库不能同步这些更新。
解决方法有两种：
- 在下游仓库中创建一个拥有`workflow`权限的`PAT`(下游用户需要进行两个额外的配置操作，增加上手成本)；
- 遇到workflow配置文件更新的情况，手动仓库页面进行更新(其他的非workflow配置文件更新可以无感同步更新)。
=> ci: update sync action

app/components/home.tsx, app/components/settings.tsx, app/locales/cn.ts, app/locales/en.ts, app/locales/tw.ts, app/store/app.ts
给发送预览气泡加个开关，这样打字时可以参照前文对话，不会被自己的预览气泡顶掉
=> feat: add switch of send preview bubble

app/store/app.ts
Bug: The length of `new Array(20).slice(20 - 24) ` is 4 which should be 24.
=> fix: fix history message count

.github/workflows/sync.yml
在配置中增加操作权限，避免下游因未在设置中开启`GITHUB_TOKEN`的write权限产生的[403报错](https://github.com/yorunning/ChatGPT-Next-Web/actions/runs/4593191664/jobs/8110891207#step:3:143)
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/316#issuecomment-1492988311
这样下游不用单独进行设置了
=> ci(sync): add push permission

app/components/chat.tsx, app/requests.ts, app/store/app.ts
- prompt 
- export chat history
=> fix: context message should exclude all error tips

app/components/chat.tsx
- 桌面端 `onWheel` 的时候再取消自动滚动更好，不然鼠标一移上去就失去焦点无法输入了。
- 移动端发送消息之后最好是收起键盘，以最大的显示空间等待GPT回复。
- 不使用`focus()` 和 `blur()` 来间接控制 `setAutoScroll` ，因为二次聚焦/失焦的时候不会触发 `onFocus`和`onBlur`。
=> optimize: scrolling experience

app/components/settings.tsx
`checkUsage()` was already called by another `useEffect`. There is no need to call it twice.
=> chore: removed redundant checkUsage

app/components/chat.tsx
Markdown rendering can take time. Use `React.memo` for better performance.
The improvement is especially visible if there are complex elements. For example, a `<Chat />` with an output of `如何推导三次方程求根方程？` (which uses latex) now renders in about 5ms, down from ~140ms.
Related: #302
=> perf: memorize markdown rendering

app/components/window.scss
=> fix: header title overflow

app/components/input-range.module.scss, app/components/input-range.tsx, app/components/settings.tsx, app/styles/globals.scss
link：https://github.com/Yidadaa/ChatGPT-Next-Web/issues/233
1. 修复bug-233，标准语法中 input 是没有 :before、 :after 伪元素的。参考（https://stackoverflow.com/questions/37653706/before-with-input-in-firefox）
2. 修改了 firefox和ie的input range样式，使其与chorme保持一致
=> fix: 兼容不同浏览器的input range

app/components/chat.tsx
当移动端用户点击输入文本框后，聊天列表应该自动滚动（与当前一致）。
但在电脑屏幕上，聊天列表不应该自动滚动，因为用户可能需要参考之前的聊天记录。
本提交将电脑屏幕中自动滚动逻辑移动到 submit 时刻。
=> fix: distinguish PC/Mobile behavior on auto-scroll

app/components/chat.tsx, app/components/settings.tsx
link: https://github.com/Yidadaa/ChatGPT-Next-Web/issues/511
在setting页面按 Escape 关闭，在chat页面当用户输入框为空时按 ArrowUp 填充上次提交的数据
=> feat: 添加对热键的支持 Escape to close settings, Up Arrow to get last input

README_CN.md
Docker 配置代理部分存在错误。容器启动后 proxychains 报错，提示不接受非数字形式的代理地址，因此将代理地址更改为 127.0.0.1，同时修改容器的网络模式为 host
=> fix docker proxy config

app/api/chat-stream/route.ts, app/api/openai/route.ts
在 Next.js 13.3.1 中， export config 被弃用，See https://beta.nextjs.org/docs/api-reference/segment-config.
=> 修复 Edge Runtime 设置失效问题

scripts/setup.sh
[[Bug] Unsupported Linux distribution when running setup.sh on Ubuntu OS](https://github.com/Yidadaa/ChatGPT-Next-Web/issues/978)
=> [Bug] Unsupported Linux distribution when running setup.sh on Ubuntu OS

app/utils.ts
When typing `<meta http-equiv="refresh" content="0;http://google.com">` in the input area, the page redirects to google.com.
Changing innerHTML to innerText will fix it.
=> fix: use innerHTML may leads unexpected script execution

scripts/fetch-prompts.mjs
the original logic
Let's take a shortened example of prompt from the remote cvs file.
which can be below:
`
"javascript console","it prints console.log(""hello world"")"
`
```
v.split('","').map((v) => v.replace('"', "")))
```
after `split` method, it becomes an array:
` [ '"javascript console', 'it prints console.log(""hello world"")"'] `
if calling ` v.replace('"', "")`, which only replace the first `"`,  the prompt becomes:
` [ '"javascript console', 'it prints console.log("hello world"")"' ] `
this is what I described in the bug report:
https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1240 
```
v.replace(/^"|"$/g, '').replaceAll('""','"')))
```
my fix is, first replace the single `"`  with '', in the head or the tail of the split elements, then replace  all `""` with `"`
=> fix: bug #1240

app/requests.ts
When we use the app behind a nginx reverse proxy with basic authorization. The `getHeader` function will reset the "Authorization" field and lead to a 401 error.
This patch resolve the problem.
=> resolve problem about basic auth when the app is behind a proxy server

app/components/settings.tsx
in `Settings` page, when checking update is on the way, it's better to show an animating icon, here i use `<LoadingIcon />`, rather than an empty `<div/>`.
=> fix: show Loading Icon when checking repo update

app/components/home.module.scss
在移动端聊天窗口滚动到边界后会触发浏览器的刷新行为，故使用overscroll-behavior: none;将其禁止
参考：https://developer.mozilla.org/zh-CN/docs/Web/CSS/overscroll-behavior
=> feat: mobile chat overscroll-behavior none

app/components/settings.module.scss
As in this snapshot, if you create empty prompts without editing the conent, nothing is wrong see **A**, but as long as you have long contents, well, the button groups starts displaying incorrectly, see **B**.
The reason is, 
```css
.user-prompt-header {
max-width: calc(100% - 100px);
}
```
it only leaves `100px` for the 3 buttons with full prompt contents.  I don't think to reduce the max width of the content is a good idea, because we also need to display the content in mobile devices.
so the only way i can do is to slim the buttons,  originally, each button has a padding of `10px`, which takes up `20 px` space, so i reduced it to `padding: 7px;`, not only that, i see the gap between two buttons from `5px` to `2px`.
by the way, I recommend using  css properties of `column-gap` or …
=> fix: styles on .user-prompt-buttons

.github/workflows/sync.yml
因为 Vercel 频繁更新会失败，遂建议改为一天同步一次。
相似pr #1262
=> feat: sync code every day instead of every hour

docs/cloudflare-pages-cn.md, docs/cloudflare-pages-en.md
添加Cloudflare Pages的部署说明。这里临时说明，Next-on-Pages有一个bug将很快修复，修复后，Build命令会修改。解决以下Requests: #982 #239 #1321
=> 添加Cloudflare Pages的部署说明

app/utils.ts
this PR fixes the remaing issues in  https://github.com/Yidadaa/ChatGPT-Next-Web/pull/1359 and https://github.com/Yidadaa/ChatGPT-Next-Web/pull/1361/commits/9b1f25140e861b72a3b783d52ca7f42e6bd966b2
for the  details, please see: https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1370
=> fix: row count logic 

app/components/chat.tsx
Allow users to click the prompt hints button to hide hints when they are already displayed.
=> Fix: click the prompt button to hide hints when it's already shown

app/components/home.tsx, app/layout.tsx
theme-color增加了 [media="(prefers-color-scheme: light)](https://github.com/Yidadaa/ChatGPT-Next-Web/commit/36adfe87fb965120a208df907a609ec235437d06#diff-eca96d2c09f31517696a26e1d0be4070e1fbab02831481bed006e275741d030bR30) 这个媒体查询后破坏了之前的 theme-color 查询规则，这个pr主要是修复了查询规则，然后把部分nextjs支持的meta标签移到了`metadata`中（如果需要之前的风格写法可以回退）
=> fix: the theme-color selector

.env.template, .gitignore, docker-compose.yml
1、Copy .env.template to .env and fill in the configuration file
`cp .env.template .env`
2、Run the docker-compose command
- no proxy
`docker-compose --profile no-proxy up -d`
- proxy
`docker-compose --profile proxy up -d`
=> Add docker-compose launch

app/client/platforms/openai.ts
deep in the source code of [fetch-event-source](https://github.com/Azure/fetch-event-source) , (not the readme markdown document). you can find something [here](https://github.com/Azure/fetch-event-source/blob/a0529492576e094374602f24d5e64b3a271b4576/src/fetch.ts#L50): 
```
/**
* If true, will keep the request open even if the document is hidden.
* By default, fetchEventSource will close the request and reopen it
* automatically when the document becomes visible again.
*/
openWhenHidden?: boolean;
```
_Sorry for I didn't know how to embed multi lines of code from another online file, I'd be glad if anybody can give me some hints or tips to do so._
this is much like [TanStack Query](https://tanstack.com/query/v3/) or  [SWR](https://swr.vercel.app/)
which stops http fetching while the …
=> fix: set openWhenHidden to be true

README.md, app/locales/cn.ts, app/locales/cs.ts, app/locales/de.ts, app/locales/en.ts, app/locales/es.ts, app/locales/fr.ts, app/locales/index.ts, app/locales/it.ts, app/locales/jp.ts, app/locales/ko.ts, app/locales/ru.ts, app/locales/tr.ts, app/locales/tw.ts, app/locales/vi.ts
=> Add Korean translation 增加国际化语言：韩语

app/api/common.ts
This commit resolves a memory leak issue that was occurring due to fetch requests hanging indefinitely. A timeout has been introduced to the `requestOpenai` function which ensures that these requests are aborted after a set period of time (currently 10 minutes). Additionally, error handling has been added to catch and log `AbortError` when a fetch request is aborted. This fix significantly improves the stability and reliability of the application by preventing memory leaks related to unresolved fetch requests.
=> fix:Fix memory leak issue by adding fetch request timeout

app/components/mask.tsx
As discussed in this ticket https://github.com/Yidadaa/ChatGPT-Next-Web/issues/1620
the original logic only supported uploading many  masks, i mean the json content of the uploading file must be in the format of array, but it ignored if the user uploads a single mask.
now I fixed the logic to support both cases. Please review the original ticket to make sure whether this PR should be merged.
=> fix: allow to import a single mask

vercel.json
使用logflare等第三方日志服务的access log中访客IP都是Vercel边缘网络的ip
添加headers以得到真实访客ip。
=> fix: get real-ip instead of vercel edge network ip

app/components/home.module.scss
this is a rather minor fix, but it resolves two issues in the UI of sidebar as in below snapshot:
1. if the content of the title is longer than 200px, it cannot fully display, regardless how rightwards you drag the sidebar.
2. if you narrow down the sidebar, you may find that the delete icon overlaps with the title.
the result after fix can be seen here:
There is a open pull request https://github.com/Yidadaa/ChatGPT-Next-Web/pull/1320 which addresses the display of title content. but in which it didn't fix the issue of 2.  so I open this PR here.
To create the long chat title, I used these questions:
```
1. what is setTimeout in javascript?
2. how far from Beijing to Tianjin?
```
=> fix: css on display chat names

app/locales/index.ts
Use DEFAULT_LANG with Node. Remove the logging on the server side:
[Lang] failed to detect user lang.
=> Not to detect user lang when running in Node

app/components/chat.tsx
As in the commit, `props.prompts.length` should be monitored in `useEfffect`, otherwise, when search prompt action changes the length of `props.prompts`, the function inside `useEfffect` doesn't re-generate at all, which still points to the initial props.prompts,  thus the bug comes out..
=> fix: bug #1662

next.config.mjs
appDir option no longer needed start from nextjs13.4 https://nextjs.org/docs/app/api-reference/next-config-js/appDir
=> clean next.config.mjs

Dockerfile, app/utils/format.ts
修复了部分情况下prettyObject方法存在入参非 string 然而 JSON.stringify 结果为{}的情况 #1732 
Docker 构建时如若存在PROXY_URL环境变量并且未指定 HOSTNAME 则 默认设置为 127.0.0.1以避免 proxychains 代理本机地址 #1556
=> fix : specify the default hostname if docker builds with a proxy

Dockerfile
修复了 #1747 #1748 所说的语法问题 （ 大意了
以及 `if [ -z "$HOSTNAME" ]; then ` 这个逻辑实际上是无效的，Docker 容器一定会有一个HOSTNAME环境变量，所以移除了判断是否不存在的逻辑
=> fix: Logical corrections & syntax errors

app/components/ui-lib.tsx
解决ListItem组件className出现undefined的问题
=> refactor: Fix undefined className in ListItem

app/utils.ts
this PR is to remove a unused function:
```
export function isMobileScreen() {
if (typeof window === "undefined") {
return false;
}
return window.innerWidth <= MOBILE_MAX_WIDTH;
}
```
because the actual `isMobileScreen` is from  the `useMobileScreen` custom hook. with the same name, this function can be confusing.
=> chore: remove unused code

app/utils/format.ts
as in the snapshot,  this bug can happen in cases like when the internet is broken, or accessing from China-based IP addresses.
I did a lot of research, finding this fix requires the minimum change of code.
=> fix: the display format of json error

app/components/home.module.scss
actually I've detected this issue for a long while. 
as in this snapshot:
when the returned content is too short, the buttons may overlap with the chatbot icon. The question I used for this answer is `reply me yes or no to my question, is 1+1=3?`
After the fix, it becomes:
=> fix: [CSS] the position of top-action buttons

app/components/chat-list.tsx
props is converted to a string when we create the component, we don't need to do it twice
https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/app/components/chat-list.tsx#L76
=> fix date time bug on chat lists

app/components/mask.tsx
当用户在`ContextPromptItem`的`Input`触发`blur`事件时，清除所有的`selection range`，避免「划词翻译」这类扩展始终显示浮动条
https://github.com/Yidadaa/ChatGPT-Next-Web/assets/35998162/83284c58-23ca-4f51-9f82-8ca9ad1da1e8
https://github.com/Yidadaa/ChatGPT-Next-Web/assets/35998162/6010a8f8-667a-4f56-9bf8-6e9c525078d6
=> fix: remove selection range when user blured

app/store/chat.ts
As stated in the documentation, all states in Zustand are immutable. Therefore, when updating arrays or nested objects, it is recommended to use immutable methods. Mutable methods like `Array.prototype.push()` may not be detected by Zustand.
Although mutable methods may still work in practice, issues may arise when using performance optimization techniques such as `useCallback` and `memo`. This suggests that the component render actually caused by parent components, rather than Zustand.
While I am not highly experienced in using Zustand, I personally prefer the immutable approach. If you prefer the mutable approach (as seen in Redux Toolkit), integrating Immer into Zustand may be a viable option.
https://docs.pmnd.rs/zustand/guides/updating-state#normal-approach …
=> fix: updating the array using push in zustand does not actually trigger component updates

package.json, yarn.lock
A vulnerability in npm package [yaml](https://www.npmjs.com/package/yaml) was discovered in April this year. Details about this vulnerability can be reviewed here: https://github.com/advisories/GHSA-f9xv-q969-pqx4.
npm package [lint-staged](https://www.npmjs.com/package/lint-staged) currently targets yaml version 2.2.1, which is an effected version of the package. This pull request resolves this issue by creating a package resolution for lint-staged, targeting version 2.2.2 and greater.
=> Remediation of CVE-2023-2251

app/components/exporter.tsx, app/locales/cn.ts, app/locales/cs.ts, app/locales/de.ts, app/locales/en.ts, app/locales/es.ts, app/locales/fr.ts, app/locales/it.ts, app/locales/jp.ts, app/locales/ko.ts, app/locales/no.ts, app/locales/ru.ts, app/locales/tr.ts, app/locales/tw.ts, app/locales/vi.ts
聊天记录导出格式为image时聊天信息项标题使用设置的语言
chat information items title using the language in the settings when exporting chat records in image format
=> feat: i18n in message exporter

app/store/config.ts
由于modelConfig新增了frequency_penalty参数，需要migrate一下，否则设置里frequency_penalty的拖动条初始值不显示。
=> fix: migrate modelConfig state

app/components/home.module.scss, app/components/home.tsx, app/components/markdown.tsx, app/locales/ar.ts, app/locales/index.ts, app/styles/markdown.scss
hi this is the modified code to support the Arabic language and right-to-left direction. Additionally, I ensured that code snippets consistently appear in ".markdown-body pre", always from left to right.
In the ".markdown-body" section, I added a condition to check for Arabic characters in the 'test' operation. If Arabic characters are found, it will reverse the language direction. This is important because the input text from the user or GPT may contain English or other languages, and we want to maintain the original writing direction.
Please review the code and confirm the point of detecting Arabic characters. Will it affect the application's performance?
`direction: /[\u0600-\u06FF]/.test(props.content) ? 'rtl' : 'ltr'"`
test demo: https://jpt-ma.vercel.app
=> Added support for Arabic language and right-to-left direction

app/components/chat.tsx
由于 useLayoutEffect 在页面渲染之前同步执行，因此具有阻塞页面渲染的能力，在某些情况下可能会导致性能问题。requestAnimationFrame 是一个动画帧请求，会在浏览器下一次重绘之前触发，用于实现平滑的动画效果。
=> refactor: 优化 useScrollToBottom

app/components/chat.tsx
when userMessageIndex === 0, pinning a message was not possible.
=> Fix Pin Message

app/components/chat.module.scss, app/components/chat.tsx, app/components/ui-lib.module.scss, app/styles/window.scss
移动端设置页面的title不应居中，这个pr不会影响移动端对话页面标题居中的特性。
before：
after:
=> fix: alignment of mobile settings page title.

app/components/chat.tsx
大神， 学习代码过程中发现的一个小小的点，887行已定义`const isUser = message.role === "user";`，此处可直接用`isUser`
=> perf : 代码细节优化

app/store/chat.ts
问题描述：摘要总结后并不会被下次对话使用
问题复现：将历史长度压缩阀值调的低一点，方便触发摘要总结，F12 发现摘要总结后的对话并没有带上摘要内容。
=> 修复摘要总结后不会被使用

app/components/settings.tsx, app/locales/ar.ts, app/locales/cn.ts, app/locales/cs.ts, app/locales/de.ts, app/locales/en.ts, app/locales/es.ts, app/locales/fr.ts, app/locales/it.ts, app/locales/jp.ts, app/locales/ko.ts, app/locales/ru.ts, app/locales/tr.ts, app/locales/tw.ts, app/locales/vi.ts, app/store/config.ts, app/store/mask.ts
This PR adds a setting to hide built-in masks. If activated, only the user-defined masks are shown.
=> feat: add setting to hide built-in masks

app/api/common.ts
Cloudflare部署时候请求报，"The cache field on RequestInitializerDict is not implemented in fetch"
nodejs原生fetch请求好像不支持cache属性，如有必要通过设置头信息 ‘Cache-Control’ 是否也能达到相同效果
=> fix: cloudflare headers

app/api/common.ts
Use `||` instead of `??` when handling varaibles in `process.env` would be better.
Otherwise, when BASE_URL = '', would catch the error that cannot connect to openai.
=> fixed openai base url if empty

app/components/home.tsx, app/styles/globals.scss
If we use `Noto Sans SC`, there are display problems when Chinese and English mixed input.
For example:
```
你0 F0
```
There are two different sizes of `0` will be displayed, because we imported multiple font families. 
So I recommend using `Noto Sans` instead of `Noto Sans SC`.
=> font family display enhance

docs/faq-cn.md
OpenAI has updated their model prices, reducing the input of GPT-3.5 to $0.0015/1000 tokens
=> Update Model Pricing.md

app/components/chat.tsx
移动端的触摸移动可以小到几像素，不应该有滚动范围，在触摸较低缓慢移动无法脱离自动滚动范围。
现在还是有低概率被强制滚动，怀疑是因为如果在文本高度变化下次检测前内移动依然会被滚动。
=> The mobile terminal ishitbottom does not perform -10

app/components/exporter.tsx
where the ChatGPTicon.src
glitches and breaks when exporting the image for the second time without refreshing the page.
=> Issue #2702 should be fixed now kiw kiw

docs/cloudflare-pages-en.md
This update resolves an error when trying to deploy an error on cloudflare.
=> fix cloudflare deployment instructions

app/store/sync.ts
Severity : High
Sanitize the 'res' object before logging it in the 'check' method of useSyncStore to prevent log injection attacks.
The 'res' object is now sanitized by extracting only the necessary properties ('status', 'statusText', and 'headers') and logging the sanitized object instead.
This ensures that only safe and expected data is logged, mitigating the risk of log injection vulnerabilities.
=> [+] CodeQL Report Fix log injection vulnerability in useSyncStore

app/components/sidebar.tsx
In useRef is non-responsive, we can't get the modified config.sidebarWidth dynamic modification value in handleMouseUp
=> fix: Width changes abruptly when dragging the sidebar (jumps)

app/components/markdown.tsx
Previously, dir="auto" only applied to paragraphs and did not affect other elements in Markdown, such as headers, lists, and tables. However, it now applies to all elements collectively as well as to individual paragraphs, by using dir="auto" in both places.
While ideally, applying dir="auto" to each individual Markdown element would be the optimal solution, as a non-developer, this is the best approach I could come up with using less code.
Also, I would love if you could add it to the input filed (where the messages are written). I am not sure how.
=> Improving Text Direction

app/components/home.tsx
Fetching "Noto Sans" from Google Fonts returns a 400 error when deploying to Netlify. We should encode the `family` parameter like [Google Fonts](https://fonts.google.com/) website does.
=> Encode google font url

app/components/auth.tsx, app/locales/ar.ts, app/locales/bn.ts, app/locales/cn.ts, app/locales/en.ts, app/locales/id.ts
[+] feat(auth.tsx): add support for resetting access token in resetAccessCode function
[+] fix(auth.tsx): fix formatting issue in resetAccessCode function
[+] feat(locales): add support for sub tips in Auth component for multiple languages :
- Add sub tips in Arabic locale (ar.ts)
- Add sub tips in Bengali locale (bn.ts)
- Add sub tips in Chinese locale (cn.ts)
- Add sub tips in English locale (en.ts)
- Add sub tips in Indonesian locale (id.ts)
Preview :
=> UI Page [Auth Page]

app/store/config.ts, app/utils.ts
I came across this project and I found it really amazing. but when I visited it and wrote a simple prompt and hit "CMD + ENTER" on MacOS, it didn't work. however with "CTR + ENTER" it worked. On MacOS it's really easy to press the "command" key instead of CTR.
I created a PR that fixes this issue, now the default key submitKey should be MetaKey on MacOS.
Hope it helps the project & community!
**DEMO**: https://nextgpteric.vercel.app/
=> Command Key (MetaKey) on MacOS as default

app/components/exporter.tsx, app/global.d.ts, app/locales/cn.ts, app/locales/en.ts, app/locales/id.ts, app/store/sync.ts, app/store/update.ts, app/utils.ts, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
Fix + Improve Logs :
[Client App [Notification]](https://github.com/Yidadaa/ChatGPT-Next-Web/commit/64a17abfe2f84e9dc205aa417f6ce9a05c7c1cd2)
[Client App Fix Issue [Bug] 'export' button does not work](https://github.com/Yidadaa/ChatGPT-Next-Web/commit/d2ad01a9ffd8fd0645013aca862c691af3c2f01f) https://github.com/Yidadaa/ChatGPT-Next-Web/issues/2884
=> Client app [Tauri]

app/components/home.tsx
似乎这里引入了一个逻辑判断错误，会导致打包之后的界面变宽变高。
=> fix: #2974 wrong padding style

app/locales/index.ts, app/store/chat.ts, app/store/config.ts
Change log
-   config.ts
-   line 72: remove type confirmation of x as x always has type 'number'
-   line 135: remove the redundant local variable
-   chat.ts
-   delete the unused import
=> Some small improvements of code

app/constant.ts, app/store/chat.ts
[+] feat(constant.ts): add new models to DEFAULT_MODELS array
Note : 
The model has 128K context
read here https://openai.com/blog/new-models-and-developer-products-announced-at-devday
=> Feat Models [GPT-4] [GPT-3.5] [128K context]

app/api/common.ts
Issue
[Proxy]  v1/chat/completions?path=v1&path=chat&path=completions
[Base Url] https:/
[Org ID]
Fetch URL:  https://v1/chat/completions?path=v1&path=chat&path=completions
[OpenAI]   [TypeError: fetch failed] {
cause:  [Error: getaddrinfo ENOTFOUND v1] {
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'v1'
}
}
=> [Fix] baseUrl is empty 

app/components/exporter.tsx, app/locales/cn.ts, app/locales/en.ts, app/locales/id.ts
[+] fix(exporter.tsx): update the text in the ExportMessageModal component to use the localized title from the locale file
[+] feat(cn.ts, en.ts, id.ts): add localized title for the Exporter Description in the respective locale files
screenshot :
=> Feat UI/UX Page Local Language [Exporter Message]

app/components/model-config.tsx
It seems hiding unavailable model gives better user experience than showing disabled, especially when using model rename feat and custom models supported by `CUSTOM_MODELS`.
For example, when using custom model, I will disable all build-in models and add a few custom models. I only want to see my custom models and select from them. Showing the disabled ones is not useful.
I came up this idea when trying to add Azure deployment selection feat https://github.com/nanaya-tachibana/ChatGPT-Next-Web/commit/24cabeb04888bc2d1585137af1c4634f67cb4a5a
=> UI (model selection): hide unavailable model options

app/api/openai/[...path]/route.ts
Currently, OpenAI has blocked the IP addresses of Vercel's Hong Kong servers, which has resulted in all users redirected to the HKG1 data center being unable to use OpenAI's services. Temporarily deploying the OpenAI route's edge function in regions other than HKG1 can provide a temporary solution to this issue.
=> config: exclude hkg1 from the deployment regions of the edge function

app/store/chat.ts
- [+] fix(chat.ts): update the memory prompt in onFinish callback
- [+] feat(chat.ts): update the current session with lastSummarizeIndex and memoryPrompt
Issue known : [Bug] Memory Prompt not stored properly in top 1 of chat list https://github.com/Yidadaa/ChatGPT-Next-Web/issues/3368
=> Fix UI/UX Page Chats [Memory Prompt] [Stored Local Storage]

.dockerignore
**What changes are made 变更的内容**
Add a `.dockerignore` file to exclude the env files when building the image locally.
添加了`.dockerignore`文件，以在本地构建镜像时排除环境变量相关文件。
**Why does it matter 变更的原因**
When developing and building the docker image locally, if a `.env` file is used to specify the API key and access code, it will be included in the image that is built locally, thus leads to a secret key leak when the image is pushed to a public docker registry. 
(This week we encountered an OpenAI API key leakage. Upon investigation, it was found to be caused by the inclusion of the `.env` file in the image.)
在本地开发和构建Docker镜像时，如果使用.env文件来指定API密钥和密码，并在本地构建镜像，`.env`文件将会包含在构建的镜像中。当该镜像被推到公开的Docker Registry时，会导致密钥泄露。
（本周遇到了OpenAI API密钥泄露的问题，经排查发现为镜像中包含`.env`文件所致）
**How the .env file is included into the …
=> ci: add .dockerignore to exclude env files to prevent potential key leakages 避免潜在的密钥泄漏

app/api/common.ts
fix the related issue: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3628
=> fix: return bearer header when using openai

app/components/emoji.tsx
- [+] fix(emoji.tsx): update emoji URL to use a new Content Delivery Network (CDN)
- [+] docs(emoji.tsx): add comment explaining the reason for switching to a new CDN
issue:
-  #3646
=> Fix [UI/UX] [Emoji] emoji URL

README_CN.md, app/client/api.ts
修改header的Accept属性以确保在某些转发服务上可以正常工作。如果不指定为"application/json"，默认是“text/event-stream”，某些转发服务会报错“Could not find acceptable representation”
=> 修改header的Accept属性以确保在某些转发服务上可以正常工作

app/api/common.ts
The latest version of the OpenAI API forced the `content-encoding` to be `brotli` in json response so if the streaming is disabled, we need to remove the `content-encoding` header from the response of openai.
This is because Vercel uses gzip to compress the response data, if we don't remove the `content-encoding` header the browser will try to decode the response with `brotli` and cause a decompression fail.
=> fix: remove the content-encoding header

package.json, yarn.lock
in version `1.5.8` of Tauri builder (Tauri CLI) It's error while building apps 
might it will break the CI/CD for [`Release App`](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/actions/workflows/app.yml)
Error Log:
```sh
Plugin function not found, cannot call nsis_tauri_utils::FindProcessCurrentUser
Error in macro CheckIfAppIsRunning on macroline 2
```
> [!TIP]
> Another tips fix a git in front-end app (e.g, using github desktop) if unable to push commit after downgrade package
Bash:
```sh
git config --unset core.hooksPath
```
=> Downgrade Tauri Builder Version

app/client/platforms/google.ts
mitigate the issue https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3703
=> fix: fix gemini pro streaming api duplicated issue

.github/workflows/deploy_preview.yml
1. vercel domain suffix secret
2. add pull_request_target
3. fix vercel alias domains scripts
=> fix: ci for vercel deployment

app/api/google/[...path]/route.ts
因为部分地区不支持 Gemini API，所以修改 vercel 可能部署的区域。
参考：
1. https://ai.google.dev/available_regions?hl=zh-cn
2. https://vercel.com/docs/edge-network/regions#region-list
=> update google api region

app/locales/jp.ts
We noticed that the Japanese translation was missing compared to the English and Chinese versions.
This pull request adds Japanese translations of code-based ChatGPT messages.
Note: Some parts of the settings screen are still missing in translation.
=> feat: Add Japanese translations for ChatGPT messages

app/components/emoji.tsx
- [+] fix(emoji.tsx): update CDN url from 'cdn.jsdelivr.net' to 'fastly.jsdelivr.net'
issues
- ChatGPTNextWeb#3965
=> Fix [UI/UX] [Emoji] Update CDN

app/constant.ts, app/store/chat.ts
> [!NOTE]  
> This `Default System Template` is more dynamic now unlike stupid hardcoded
=> Improve Default System Template

app/client/api.ts, app/client/platforms/google.ts, app/client/platforms/openai.ts, app/components/exporter.tsx, app/components/home.tsx, app/components/model-config.tsx, app/constant.ts, app/store/access.ts, app/store/chat.ts, app/utils/cors.ts, next.config.mjs, package.json, scripts/setup.sh, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/tauri.conf.json
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3992
=> fix: fix gemini issue when using app

src-tauri/Cargo.toml, src-tauri/tauri.conf.json
fix this [issue](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3984) by this [flag](https://tauri.app/v1/api/config/#securityconfig.dangeroususehttpscheme).
=> fix: add support to http scheme.

app/store/config.ts
Fix temperature range according to OpenAI's official [API documentation](https://platform.openai.com/docs/api-reference/chat/create#chat-create-temperature).
> What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.
=> Fix temperature range

app/client/api.ts
ref: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4030
doc: https://docs.nextchat.dev/models/ollama
=> chore: adjust for ollama support

app/components/chat.tsx, src-tauri/tauri.conf.json
resolve following issue:
Preview video:
https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/assets/157469842/44944a49-9f04-4483-8bb2-9db1eceb9401
=> feat: auto detach scrolling

app/components/chat.tsx, app/components/emoji.tsx, app/components/settings.module.scss, app/components/settings.tsx, app/components/ui-lib.module.scss, app/components/ui-lib.tsx
修复在移动端进行修改头像的时候，EmojiPicker超出屏幕外导致不好选的问题，并添加背景颜色，修改后后如下：
=> Fix EmojiPicker mobile width adaptation and update avatar clicking behavior

package.json
Certain Continuous Integration (CI) systems, such as [Cloudflare Pages](https://pages.cloudflare.com/), use the latest version of Yarn by default, whereas `ChatGPT-Next-Web` utilizes Yarn 1.
This Pull Request (PR) adds the [`packageManager` field](https://nodejs.org/api/packages.html#packagemanager) to the `package.json` file, specifying that Yarn 1 should be used. This enables Cloudflare Pages to automatically install and select Yarn 1 for the build process.
This also simplifies the process for contributors who use [corepack](https://nodejs.org/api/corepack.html), enabling them to switch their package manager automatically.
=> chore: specify yarn 1 in package.json

app/components/chat.tsx
Fix Chinese input method "Enter" on Safari #4297
=> Fix "Enter" bug

app/client/platforms/openai.ts
在这次提交中，我针对本地使用的模型在处理问答提交时可能出现的问题进行了改善。具体场景是：当用户提交一个问题后，由于模型原因已经结束了但是未能返回任何信息时，界面会持续显示加载状态，而无任何反馈给用户。为了解决这一问题，本次提交增加了对已结束但返回结果长度为零情况的处理逻辑
=> Fix: Handle empty server response in API call

app/components/markdown.tsx
解决gpt回复的公式使用 \\(...\\) 和 \\[...\\] 格式导致的渲染问题  https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/3436#issuecomment-1842626873
remark-math 里有人讨论了这个问题，不过结论是不会支持这种格式 https://github.com/remarkjs/remark-math/issues/39
曾尝试用rehype-mathjax来代替rehype-katex，不过也没有正确渲染
最后参考了这里的实现，把\\(...\\) 和 \\[...\\]格式替换为美元符号：
https://github.com/danny-avila/LibreChat/pull/1585
https://github.com/danny-avila/LibreChat/blob/v0.6.10/client/src/utils/latex.ts#L36
现在的效果：
此前的效果：
=> support \(...\) and \[...\] style math formula

app/utils/cloud/webdav.ts
我使用了 [dufs][dufs] 去搭建 webdav server, 当使用 `MKCOL` method 创建一个已存在的路径时，它会返回 405，但是 ChatGPT-Next-Web 中使用了 `MKCOL` method 去探测可用性，所以每次探测都会失败
所以在 check 函数中加上了 `405` 这个状态码
或者我觉得应该换一种方式去 check，而不是使用 `MKCOL` 这种方式？
[dufs]: https://github.com/sigoden/dufs
=> fix: webdav check httpcode list

app/components/chat-list.tsx
This PR fixes the border of ChatItem still showing in other pages.
https://github.com/ChatGPTNextWebTeam/ChatGPT-Next-Web/assets/53571741/4ca119d4-420b-43c8-9de1-e210efdc35e0
=> fix(chat-item): selected ChatItem showing border in other pages

.env.template, app/api/anthropic/[...path]/route.ts, app/api/auth.ts, app/client/api.ts, app/client/platforms/anthropic.ts, app/client/platforms/openai.ts, app/components/exporter.tsx, app/components/home.tsx, app/components/settings.tsx, app/config/server.ts, app/constant.ts, app/locales/cn.ts, app/locales/en.ts, app/locales/pt.ts, app/locales/sk.ts, app/locales/tw.ts, app/store/access.ts, app/store/chat.ts, app/typing.ts, app/utils.ts, app/utils/object.ts, next.config.mjs
Added support for various versions of the claude model
=> Feat multi models

app/store/chat.ts
**以前的效果（提问的时间是北京时间2024年4月12日23:00，但gpt误以为是utc时间）：**
**修改后的效果：**
=> add timezone in system prompts

app/components/mask.tsx
Prevents reading `localStorage` every time the `<MaskPage />` renders.
=> perf: avoid read localStorage on every render

app/constant.ts
This PR refactors the `DEFAULT_MODELS` array to improve code maintainability and readability. Instead of hard-coding each model object, it now uses a more concise approach by iterating over arrays of model names for each provider (OpenAI, Google, and Anthropic). This approach makes it easier to add, remove, or modify models in the future.
=> Refactor DEFAULT_MODELS for better maintainability

app/api/config/route.ts, app/components/chat.tsx, app/config/server.ts, app/store/access.ts, app/utils/hooks.ts, app/utils/model.ts
A new **optional env `DEFAULT_MODEL`** is supported now.
For example:
```bash
docker run --rm  -p 63000:3000 \
-e OPENAI_API_KEY=sk-jKxxxxxxxxxxxxxxxxxxxxxxxxx \
-e CODE=jalr4ever \
-e BASE_URL=https://api.proxychat.com.cn \
-e HIDE_USER_API_KEY=1 \
-e CUSTOM_MODELS=-all,+gpt-3.5-turbo-0613,+gpt-3.5-turbo-0301,+gpt-3.5-turbo-16k,+gpt-4-turbo,+gpt-4-0125-preview,+gemini-pro \
-e DEFAULT_MODEL=gpt-4-turbo \
-e GOOGLE_API_KEY=AIzaaaaaaaaaaaaaaaaaaaa \
-e GOOGLE_URL=https://mellifluous-aaaaaaaaaa.app \
jalr4ever/chatgpt-next-web:v2.11.3 
```
The feature version is already published in docker hub, you can just simply run `docker pull jalr4ever/chatgpt-next-web:v2.11.3` for usage preview.
=> Support a way to define default model by adding DEFAULT_MODEL env.

app/client/platforms/google.ts, app/constant.ts
Refer to [OpenAI documentation](https://platform.openai.com/docs/models/overview) to delete some models.
Optimise some code.
参考 [OpenAi 官方文档](https://platform.openai.com/docs/models/overview)，整合部分模型。
优化部分代码
=> Refer to OpenAI documentation to delete some models.

app/styles/globals.scss
好像chrome前几个版本开始，部分页面元素在`:focus-visible`的时候会带上outline边框。
比如聊天界面内，点击空白区域，随后点击shift，则会触发。其余地方暂时不会，但是通过devtools手动添加`:focus-visible`后就会显现。
暂时在body中全局修改，如果有需要注意的地方还请指出来。
=> chore: No outline when element is in `:focus-visible` state

app/client/platforms/openai.ts
The official version of gpt4 turbo no longer requires the "max_tokens" field
=> remove max_tokens from the official version of gpt4-turbo

Dockerfile
close https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/4795
issue mentioned here would appear again: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/pull/1738
=> fix: revert proxy url changes

app/api/anthropic/[...path]/route.ts, app/api/common.ts, app/client/platforms/anthropic.ts, app/client/platforms/openai.ts, app/utils/cloudflare.ts
rebuild fetchUrl, if using cloudflare ai gateway
#4976 #4926 #3347 #4405 #3079
=> support cloudflare ai gateway

app/components/chat.module.scss, app/components/chat.tsx
=> feat: add model name to conversation page

app/components/chat.tsx, app/locales/ar.ts, app/locales/bn.ts, app/locales/cn.ts, app/locales/cs.ts, app/locales/de.ts, app/locales/en.ts, app/locales/es.ts, app/locales/fr.ts, app/locales/id.ts, app/locales/it.ts, app/locales/jp.ts, app/locales/ko.ts, app/locales/no.ts, app/locales/pt.ts, app/locales/ru.ts, app/locales/sk.ts, app/locales/tr.ts, app/locales/tw.ts, app/locales/vi.ts, app/store/chat.ts
添加按钮使得标题可以手动更新
split from #5426 
标题刷新按钮在手机上的布局可能不好看（不对称），但我一时间也想不到更好的布局方案。
现在手动刷新标题发送的历史长度基于用户在模型设置里设置的发送历史的长度，最短为最近的一条历史消息。
=> feat: menual regen title

app/store/prompt.ts
Running fetch with a relative path in not possible server side. To avoid the fetching server side, checking if `window` is undefined and doing an early return if so resolves the issue.
This fix should resolve:
- [https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5412](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5412)
- [https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5423](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/issues/5423)
=> fix: Avoid fetching prompts.json serverside

app/api/google.ts, app/client/api.ts, app/client/platforms/google.ts
=> google api using `x-google-api-key` header

app/components/home.module.scss, app/components/sidebar.tsx
=> fix: sidebar style

.github/workflows/deploy_preview.yml
=> update deploy_preview run target

app/components/chat.tsx, app/store/chat.ts
=> fix: updateCurrentSession => updateTargetSession

app/config/server.ts, app/utils/model.ts, test/model-available.test.ts
=> fix: failed unit test

app/icons/llm-icons/grok.svg, app/icons/llm-icons/moonshot.svg, app/icons/llm-icons/openai.svg
Fix: Set consistent fill color for OpenAI/MoonShot/Grok SVG to prevent color inversion in dark mode
The icons introduced in commit add9ca2 displayed incorrectly in dark mode. This update fixes the issue for the OpenAI, MoonShot, and Grok icons.
Commit add9ca2 引入的部分图标在暗黑模式下显示异常，本次更新修正了OpenAI/MoonShot/Grok等3个图标的该问题。
The fill color has been specified to prevent changes with the parent element's color in dark mode. No other changes are involved.
指定了填充颜色，以避免暗黑模式下随父元素颜色变化，不涉及其他更改。
=> Fix: Set consistent fill color for OpenAI/MoonShot/Grok SVG to prevent color inversion in dark mode
